# Start with the official Node.js image.
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json to the workdir
COPY package.json .

# Install dependencies
RUN npm install

COPY . .

# daemon off; tells Nginx to run in the foreground
CMD ["npm", "start"]
