apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: simple-app-dev
build:
  local:
    push: false
  artifacts:
  - image: simple-app-dev
    docker:
      dockerfile: Dockerfile.dev
    sync:
      infer:
      # sync all files to container
      - "**/*"
manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/nodePort.yaml
